const occupationList = [
  'Armeiro(a)',
  'Astrólogo(a)',
  'Fabricante de Bolsas',
  'Padeiro(a)',
  'Fabricante de Cestos',
  'Fabricante de Cintos',
  'Ferreiro(a)',
  'Fabricante de Vassouras',
  'Açougueiro(a)',
  'Carpinteiro(a)',
  'Cartógrafo(a)',
  'Queimador(a) De Carvão',
  'Fabricante de Queijos',
  'Sapateiro(a)',
  'Cozinheiro(a)',
  'Bêbado(a)',
  'Agricultor(a)',
  'Pescador(a)',
  'Bardo(a)',
  'Soprador(a) de Vidros',
  'Pedinte',
  'Agiota',
  'Apostador(a)',
  'Coletor(a) de Bosta',
  'Coveiro(a)',
  'Carniceiro(a)',
  'Pergaminheiro(a)',
  'Caçador(a)',
  'Golpista',
  'Joalheiro(a)',
  'Ladra(ão) de Corpos',
  'Carcereiro(a)',
  'Caçador(a) de Ratos',
  'Pedreiro(a)',
  'Contrabandista',
  'Lenhador(a)',
  'Alquimista',
  'Profeta de Rua',
  'Engenheiro(a)',
  'Falcoeiro(a)',
  'Fabricante de Chaves',
  'Contador(a) de Histórias',
  'Coletor(a) de Impostos',
  'Vigarista'
]

export default function getOccupation() {
  return occupationList[Math.floor(Math.random() * occupationList.length)]
}
